# Author: Pritam Raha <rahapritam32@gmail.com>
# Generated by Django 6.0.7 on 2026-08-01.

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentOnboarding',
            fields=[
                ('submission_id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('schema_version', models.CharField(choices=[('1.0', '1.0')], max_length=3)),
                ('submitted_at', models.DateTimeField()),
                ('organisation_id', models.UUIDField(db_index=True)),
                ('student_external_id', models.CharField(max_length=32)),
                ('student_first_name', models.CharField(max_length=50)),
                ('student_last_name', models.CharField(max_length=50)),
                ('student_date_of_birth', models.DateField()),
                ('emirate', models.CharField(choices=[('ABU_DHABI', 'Abu Dhabi'), ('AJMAN', 'Ajman'), ('DUBAI', 'Dubai'), ('FUJAIRAH', 'Fujairah'), ('RAS_AL_KHAIMAH', 'Ras Al Khaimah'), ('SHARJAH', 'Sharjah'), ('UMM_AL_QUWAIN', 'Umm Al Quwain')], max_length=18)),
                ('school_name', models.CharField(max_length=120)),
                ('learning_support_required', models.BooleanField()),
                ('has_formal_diagnosis', models.BooleanField()),
                ('diagnosis_codes', models.JSONField(default=list)),
                ('guardian_full_name', models.CharField(max_length=101)),
                ('guardian_email', models.EmailField(max_length=254)),
                ('guardian_phone_e164', models.CharField(max_length=16)),
                ('guardian_relationship', models.CharField(choices=[('FOSTER_GUARDIAN', 'Foster guardian'), ('LEGAL_GUARDIAN', 'Legal guardian'), ('PARENT', 'Parent')], max_length=16)),
                ('consent_to_process', models.BooleanField()),
                ('consent_timestamp', models.DateTimeField()),
                ('support_areas', models.JSONField(default=list)),
                ('requested_hours_per_week', models.PositiveSmallIntegerField()),
                ('preferred_language', models.CharField(choices=[('ARABIC', 'Arabic'), ('ENGLISH', 'English'), ('HINDI', 'Hindi'), ('MALAYALAM', 'Malayalam'), ('TAMIL', 'Tamil'), ('URDU', 'Urdu')], max_length=9)),
                ('wheelchair_access_required', models.BooleanField()),
                ('dcyn_all_rules_passed', models.BooleanField(default=True, editable=False)),
                ('dcyn_failed_rule_ids', models.JSONField(default=list, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'student_onboarding',
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['organisation_id', 'student_external_id'], name='onboard_org_student_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('requested_hours_per_week__gte', 0), ('requested_hours_per_week__lte', 40)), name='onboarding_hours_between_0_and_40'), models.CheckConstraint(condition=models.Q(('consent_to_process', True)), name='onboarding_requires_processing_consent'), models.CheckConstraint(condition=models.Q(('dcyn_all_rules_passed', True)), name='onboarding_requires_all_dcyn_rules')],
            },
        ),
    ]
